on:
  push:
    branches:
    - main
jobs:
  build:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v2
    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - name: NPM CI
      run: npm ci
    - name: Affichage du repertoire
      run: |
        echo "Structure of work folder of this pipeline:"
        tree ${{ env.Agent.WorkFolder }}\1 /f

        echo "Build.ArtifactStagingDirectory:" 

        echo "${{ github.workspace }}"

        echo "Build.BinariesDirectory:" 

        echo "${{ env.Build.BinariesDirectory }}"

        echo "Build.SourcesDirectory:"

        echo "${{ github.workspace }}"
    - name: Building Vue app
      run: .\node_modules\.bin\vue-cli-service build
    - name: Install firebase tools
      run: npm install -g firebase-tools
      shell: cmd
    - name: Connexion a Firebase
      run: firebase login --no-localhost
      shell: cmd
    - name: firebase publish -m "${{ github.run_number }}"
      run: firebase deploy --token "${{ env.FIREBASE_TOKEN }}" -m "${{ github.run_number }}"
      shell: cmd
